"use client";
import {displayedVotes,voteCountCaption} from "@/lib/vote-tally";
import {useMemo,useState} from "react";
import {ArrowUpRight,CheckCheck,Clock3,Feather,Search,ShieldCheck,Users,Waypoints} from "lucide-react";
import {DID_PATTERN} from "@/lib/signatures";
import {lettersOf,shortDid,roomLink,LAUNCH,ROOM,type Snapshot,type Team,type Writer,type Message} from "@/lib/sonnet-types";
import {messageBody} from "@/lib/sonnet-projector";
import {teamFit,routeWords,canWrite,SAMPLE_WORDS} from "@/lib/team-fit";
import {loadLexicon,checkWord} from "@/lib/word-check";
export {tableStatusLabel as statusLabel} from "@/lib/table-lifecycle";
import {tableWaiting} from "@/lib/membership-status";
import {tableStatusLabel as statusLabel, seatsClosed} from "@/lib/table-lifecycle";
export function LetterChips({letters,highlight=""}:{letters:string;highlight?:string}){return <span className="letter-chips">{[...letters].map(l=><b key={l} className={highlight.includes(l)?"letter-match":""}>{l.toUpperCase()}</b>)}</span>;}
function Source({message,label="Source"}:{message:Message|null|undefined;label?:string}){return message?<a className="evidence-link" href={roomLink(message.room,message.seq)} target="_blank" rel="noreferrer">{label} #{message.seq}<ArrowUpRight size={13}/></a>:null;}
export function LiveStatus({snapshot}:{snapshot:Snapshot}){return <div className="live-status"><div><ShieldCheck size={18}/><span><strong>{snapshot.launchSeen?"Official referee verified":"Checking the official launch"}</strong><small>{snapshot.launchSeen?"Acceptance labels come from signed referee receipts.":"Membership will remain unconfirmed until verification succeeds."}</small></span></div><a href={LAUNCH} target="_blank" rel="noreferrer">Launch record<ArrowUpRight size={14}/></a></div>;}
export function TeamFacts({team,did="",compact=false}:{team:Team;did?:string;compact?:boolean}){
 const fit=DID_PATTERN.test(did)?teamFit(did,team):null;
 return <div className={`team-facts ${compact?"compact":""}`}>
  {!seatsClosed(team)&&team.availableRequest&&<div className="recruitment-line"><Users size={14}/><span>{team.openSeats===null?"Recruiting writers":`${team.openSeats} seat${team.openSeats===1?"":"s"} advertised`}<small>Host announcement · confirm availability</small></span><Source message={team.recruitment}/></div>}
  {!seatsClosed(team)&&team.requestedLetters&&team.availableRequest&&<div className="need-line"><span>Looking for</span><LetterChips letters={team.requestedLetters} highlight={fit?.requested}/></div>}
  {!compact&&team.recruitment&&<div className="recruitment-quote"><p>{messageBody(team.recruitment)}</p><Source message={team.recruitment} label="Host's original message"/></div>}
  <div className="blocker-line"><Clock3 size={14}/><span>{team.status==="submitted"||team.status==="completed"?tableWaiting(team,[]):team.blockers[0]??"Read the latest room state"}</span></div>
  {!compact&&<><div className="milestones"><span className={team.setupReceipt?"done":""}>Room {team.setupReceipt?"allocated":"pending"}</span><span className={team.confirmed?"done":""}>Roster {team.confirmed?"ready":`${team.acceptedConsents.length}/${team.members.length||"?"} approved`}</span><span className={team.frozen?"done":""}>First word {team.frozen?"accepted":"pending"}</span><span className={team.status==="submitted"?"done":""}>Submission {team.status==="submitted"?"accepted":"pending"}</span></div>{team.status!=="submitted"&&team.status!=="completed"&&team.blockers.slice(1).map(b=><p className="detail-blocker" key={b}>{b}</p>)}<div className="source-links"><Source message={team.setupReceipt} label="Room setup"/><Source message={team.rosterReceipt} label="Roster receipt"/><Source message={team.lastReceipt} label="Latest acceptance"/></div><p className="fine-print">Team-room check: {team.lastCheckedAt?new Date(team.lastCheckedAt).toLocaleString():"pending"}. A recent discovery post does not prove this room is current.</p></>}
 </div>;
}
export function MatchDesk({snapshot,initialDid,onOpen}:{snapshot:Snapshot;initialDid:string;onOpen:(id:string)=>void}){
 const [input,setInput]=useState(initialDid),[showAll,setShowAll]=useState(false);const valid=DID_PATTERN.test(input.trim()),did=input.trim();
 const writer=snapshot.writers.find(w=>w.did===did);
 const candidates=useMemo(()=>valid?snapshot.teams.filter(t=>!t.closed&&!t.frozen&&t.members.length<8).map(t=>({team:t,fit:teamFit(did,t)})).sort((a,b)=>Number(b.team.availableRequest)-Number(a.team.availableRequest)||b.fit.requested.length-a.fit.requested.length||b.fit.newWords.length-a.fit.newWords.length||Number(!!b.team.setupReceipt)-Number(!!a.team.setupReceipt)):[],[snapshot.teams,did,valid]);
 return <section className="match-desk"><div className="section-intro"><span className="eyebrow">FIND WHERE YOU CAN HELP</span><h2>Your letters. Their next word.</h2><p>Enter any DID to inspect its teams and useful matches. No connection or signature is needed.</p></div><label className="match-input"><Search size={19}/><input value={input} onChange={e=>setInput(e.target.value)} placeholder="did:key:z6Mk…" aria-label="DID to match" spellCheck={false}/></label>{input&&!valid&&<p className="inline-warning">Paste the complete existing Ed25519 DID.</p>}
 {valid&&<><div className="identity-result"><div><strong>{writer?.name??shortDid(did)}</strong><span>{writer?.registration==="confirmed"?"Writer registration accepted":writer?.registration==="rejected"?"Registration rejected · inspect receipt":"Writer registration not verified"}</span><Source message={writer?.receipt} label="Registration"/></div><LetterChips letters={lettersOf(did)}/><p>Missing <b>{[..."abcdefghijklmnopqrstuvwxyz"].filter(l=>!lettersOf(did).includes(l)).join(" · ").toUpperCase()||"none"}</b></p></div>
 <div className="identity-teams"><strong>Where this DID appears</strong>{writer?.teams.length?writer.teams.map(id=><button key={id} onClick={()=>onOpen(id)}>{id}<span>{writer.confirmedTeams?.includes(id)?"Confirmed roster":"Proposed roster"}</span><ArrowUpRight size={14}/></button>):<p>No roster observed. This does not establish availability.</p>}{writer?.applications?.map(id=><button key={"app"+id} onClick={()=>onOpen(id)}>{id}<span>Application observed</span><ArrowUpRight size={14}/></button>)}</div>
 <h3 className="subsection-title">Where your DID could help</h3><p className="fine-print">Ordered by advertised needs, then words you add to a fixed 60-word sample. This is a comparison, not a guaranteed seat or a poetry score.</p><div className="match-results">{candidates.slice(0,showAll?100:6).map(({team,fit})=><article key={team.id}><div><strong>{team.id}</strong><small>{statusLabel(team)}</small></div><div>{fit.requested?<><span>Requested letters you have</span><LetterChips letters={fit.requested}/></>:<span>No matching explicit letter request observed</span>}<p>{fit.newWords.length?<>You add sample words: <b>{fit.newWords.slice(0,6).join(", ")}</b></>:<>You can back up <b>{fit.backupWords.length}</b> sample words currently dependent on one writer.</>}</p></div><button className="button" onClick={()=>onOpen(team.id)}>Inspect table<ArrowUpRight size={14}/></button></article>)}</div>{candidates.length>6&&<button className="text-button" onClick={()=>setShowAll(!showAll)}>{showAll?"Show fewer":"Show all matching tables"}</button>}{!candidates.length&&<p className="inline-info">No open recruitment match can be inferred from this snapshot. Browse the source room for newer announcements.</p>}</>}
 {!valid&&<div className="match-explainer"><Waypoints size={28}/><div><strong>A word must belong to one writer.</strong><p>Two DIDs covering all 26 letters together may still be unable to write a particular word. Matches check each writer's own alphabet and useful backup coverage.</p></div></div>}
 </section>;
}
export function LetterExchange({snapshot,onOpen,onInspect}:{snapshot:Snapshot;onOpen:(id:string)=>void;onInspect:(did:string)=>void}){
 const [letter,setLetter]=useState("");const teams=snapshot.teams.filter(t=>t.availableRequest&&!t.closed&&!t.frozen&&(!letter||t.requestedLetters.includes(letter)));
 const writers=snapshot.writers.filter(w=>w.available&&!w.teams.length&&(!letter||w.letters.includes(letter)));
 return <section className="letter-exchange"><div className="section-intro"><span className="eyebrow">THE LETTER EXCHANGE</span><h2>Someone has the word you need.</h2><p>Host requests and writers who say they are available, each linked to the original signed message.</p></div><div className="alphabet-filter"><button className={!letter?"active":""} onClick={()=>setLetter("")}>All</button>{[..."abcdefghijklmnopqrstuvwxyz"].map(l=><button className={letter===l?"active":""} key={l} onClick={()=>setLetter(letter===l?"":l)} aria-label={`Filter by letter ${l.toUpperCase()}`}>{l.toUpperCase()}</button>)}</div><div className="exchange-columns"><div><h3>Tables recruiting <span>{teams.length}</span></h3>{teams.map(t=><article className="exchange-card" key={t.id}><button className="exchange-title" onClick={()=>onOpen(t.id)}>{t.id}<ArrowUpRight size={17}/></button><TeamFacts team={t} compact/></article>)}{!teams.length&&<p className="inline-info">No matching host announcement in the indexed records.</p>}</div><div><h3>Writers seeking a seat <span>{writers.length}</span></h3>{writers.slice(0,40).map(w=><article className="exchange-card" key={w.did}><button className="exchange-title" onClick={()=>onInspect(w.did)}>{w.name}<ArrowUpRight size={17}/></button><p className="fine-print">{w.registration==="confirmed"?"Writer registration accepted":"Registration not verified"} · self-reported availability</p><LetterChips letters={w.letters} highlight={letter}/><p className="writer-note">{w.availabilitySource?messageBody(w.availabilitySource):w.note}</p><Source message={w.availabilitySource}/></article>)}{!writers.length&&<p className="inline-info">No matching availability statement. Silence does not mean someone is free.</p>}</div></div></section>;
}
export function PoemWorkshop({team,writers}:{team:Team;writers:Writer[]}){
 const [draft,setDraft]=useState(""),[check,setCheck]=useState<string[]>([]),[busy,setBusy]=useState(false);
 const routing=useMemo(()=>routeWords(draft,team.members,team.lastWriter),[draft,team.members,team.lastWriter]);
 const name=(did:string)=>writers.find(w=>w.did===did)?.name??shortDid(did);
 return <section className="poem-workshop"><h3><Feather size={17}/> Table word planner</h3><p>Try a word, a line or a draft. This stays in this tab until you choose to post a signed planning message.</p><label className="field-label">Words to check<textarea rows={4} maxLength={4000} value={draft} onChange={e=>{setDraft(e.target.value);setCheck([]);}} placeholder="Try a line your team wants to write"/></label>{!team.members.length&&<p className="inline-warning">A proposed roster is needed to identify each word's possible writers.</p>}
 {draft.trim()&&team.members.length>0&&<><div className="routing-state">{routing.feasible?<CheckCheck size={17}/>:<Clock3 size={17}/>}<span>{routing.feasible?`An alternating route exists${routing.allContribute?" and includes every member":"; this draft does not yet include every member"}.`:"This sequence has no valid alternating route for the observed roster."}</span></div><div className="word-routing">{routing.rows.map((r,i)=><div key={i} className={!r.owners.length?"blocked":r.owners.length===1?"single-owner":""}><strong>{r.word}</strong><small>{routing.path[i]?name(routing.path[i]):r.owners.length?r.owners.map(name).join(" / "):"No writer has every letter"}</small><span>{r.owners.length} possible writer{r.owners.length===1?"":"s"}</span></div>)}</div>{routing.truncated&&<p className="inline-warning">Only the first 250 words were checked.</p>}<button className="button" disabled={busy} onClick={async()=>{setBusy(true);try{const lex=await loadLexicon();setCheck(draft.trim().split(/\n+/).filter(Boolean).map((line,i)=>{let sum=0;for(const w of line.trim().split(/\s+/)){const owner=team.members.find(d=>canWrite(d,w));if(!owner)return `Line ${i+1}: no member can write “${w}”.`;try{sum+=checkWord(w,owner,lex);}catch(e){return `Line ${i+1}: ${e instanceof Error?e.message:"invalid word"}`;}}return `Line ${i+1}: ${sum}/10 dictionary syllables${sum===10?" · exact ten":sum>10?" · too long":" · incomplete"}`;}));}catch(e){setCheck([e instanceof Error?e.message:"Dictionary unavailable"]);}finally{setBusy(false);}}}>{busy?"Checking dictionary…":"Check dictionary & syllables"}</button>{check.map((s,i)=><p className="check-line" key={i}>{s}</p>)}</>}
 <details className="advanced"><summary>Sample vocabulary coverage</summary><p>A fixed 60-word sample for comparing rosters; this is not a poem recommendation.</p><div className="sample-vocabulary">{SAMPLE_WORDS.map(w=><span key={w} className={team.members.some(d=>canWrite(d,w))?"covered":"uncovered"} title={team.members.filter(d=>canWrite(d,w)).map(name).join(", ")||"No member can write this word"}>{w}</span>)}</div></details>
 </section>;
}
export function SonnetGallery({snapshot,onOpen}:{snapshot:Snapshot;onOpen:(id:string)=>void}){
 const poems=useMemo(()=>snapshot.teams.filter(t=>t.words.length||t.frozen||t.status==="submitted").map(t=>({t,key:Math.random()})).sort((a,b)=>a.key-b.key).map(x=>x.t),[snapshot.teams]);
 return <section className="sonnet-gallery"><div className="section-intro"><span className="eyebrow">WATCH THE POEMS TAKE SHAPE</span><h2>One word becomes fourteen lines.</h2><p>Only referee-accepted turns appear as poem text. Completed poems, X publication and accepted submissions are separate stages.</p></div>{poems.length?<div className="gallery-grid">{poems.map(t=><article key={t.id}><div className="gallery-header"><strong>{t.id}</strong><span>{statusLabel(t)}</span></div><div className="gallery-poem">{t.lines.length?t.lines.map((l,i)=><p key={i}>{l}</p>):<p>{t.words.join(" ")||"Accepted-turn history is being reconciled."}</p>}</div><div className="gallery-footer"><span>{t.words.length} accepted words{t.entryId?` · ${displayedVotes(t)} ${voteCountCaption(t)}`:""}</span><button className="button" onClick={()=>onOpen(t.id)}>Open poem<ArrowUpRight size={14}/></button></div></article>)}</div>:<div className="empty-board"><Feather size={30}/><h3>No accepted poem text observed yet.</h3><p>Preparatory drafts in discovery and the abandoned sonnet-1 rooms are not completed entries. Provisioned team rooms are scanned in turn.</p><a className="button" href={roomLink(ROOM.results)} target="_blank" rel="noreferrer">Official results room<ArrowUpRight size={14}/></a></div>}</section>;
}
