"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {ArrowUpRight,CheckCheck,Copy,Download,ExternalLink,KeyRound,Layers3,LoaderCircle,RefreshCw,Share2,ShieldCheck,Trophy,Vote} from 'lucide-react';
import {apiUrl} from '@/lib/client-urls';
import {DID_PATTERN} from '@/lib/signatures';
import {roomLink,shortDid} from '@/lib/sonnet-types';
import {profileShareText,profileTier,type MemberProfile as Profile,type ProfileTable} from '@/lib/member-profile';
import {renderProfileCard} from '@/lib/profile-card';

export function MemberProfile({did,verified,connect,onOpen,notify}:{did:string;verified:boolean;connect:()=>void;onOpen:(id:string)=>void;notify:(text:string)=>void}){
 const [data,setData]=useState<Profile|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const refresh=useCallback(async(signal?:AbortSignal)=>{if(!DID_PATTERN.test(did))return;setBusy(true);try{const r=await fetch(apiUrl(`/api/profile?did=${encodeURIComponent(did)}`),{cache:'no-store',signal});const p=await r.json() as Profile&{error?:string};if(!r.ok)throw Error(p.error??'Profile unavailable.');if(!signal?.aborted){setData(p);setError('');}}catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:'Profile unavailable.');}finally{if(!signal?.aborted)setBusy(false);}},[did]);
 useEffect(()=>{const controller=new AbortController();void refresh(controller.signal);const timer=setInterval(()=>{if(document.visibilityState==='visible')void refresh(controller.signal);},30000);return()=>{controller.abort();clearInterval(timer);};},[refresh]);
 const profile=data?.did===did?data:null;
 if(!did)return <section className="member-profile"><div className="profile-intro"><KeyRound size={28}/><h2>Your identity. Your record.</h2><p>See your tables, accepted poems and ballot history. Verify your existing key to share your achievement badge.</p><button className="button primary" onClick={connect}>Connect your DID</button></div></section>;
 const tables=(items:ProfileTable[],empty:string)=>items.length?<div className="profile-table-list">{items.map(t=><article key={`${t.room}:${t.generation}`}><div><strong>{t.id}</strong><span>{t.status==='submitted'?'Submission accepted':t.status==='completed'?'Poem complete · submission pending':t.status==='writing'?'Writing together':t.status==='ready'?'Ready to write':'Roster forming'}</span></div><button className="text-button" onClick={()=>onOpen(t.id)}>Open table<ArrowUpRight size={15}/></button>{t.receipt&&<a href={roomLink(t.receipt.room,t.receipt.seq)} target="_blank" rel="noreferrer">Referee record<ExternalLink size={13}/></a>}</article>)}</div>:<p className="profile-empty">{empty}</p>;
 return <section className="member-profile"><header className="profile-heading"><div><span className="eyebrow">{verified?'MY PROFILE':'PUBLIC PROFILE'}</span><h2>{profile?.person?.registration==='confirmed'?profile.person.name:shortDid(did)}</h2><span className={`profile-proof ${verified?'proof-confirmed':''}`}><ShieldCheck size={16}/>{verified?'Key control verified in this tab':'Viewing public records · key control not verified'}</span></div><button className="button" disabled={busy} onClick={()=>void refresh()}><RefreshCw size={16} className={busy?'spin':''}/>Refresh</button></header>
 <p className="profile-did">{did}</p>{!verified&&<button className="text-button" onClick={connect}>This is my DID · verify my key<KeyRound size={15}/></button>}
 {error&&<p className="inline-warning" role="alert">{error}</p>}
 {!profile?<div className="profile-loading"><LoaderCircle className="spin"/><p>Checking this DID’s signed participation…</p></div>:<>
 <div className="profile-layout"><div className="profile-art-column"><AchievementBadge profile={profile} verified={verified} notify={notify}/></div><div className="profile-record-column">
 <div className="profile-metrics"><article><Trophy/><strong>{profile.historyReady?profile.completed.length:profile.completed.length?`${profile.completed.length}+`:'—'}</strong><span>Accepted poems</span></article><article><Layers3/><strong>{profile.active.length}</strong><span>Current tables</span></article><article><Vote/><strong>{profile.currentVote?'1':'0'}</strong><span>Accepted vote on record</span></article></div>
 <section className="profile-section"><h3><Layers3 size={19}/> My current tables</h3>{tables(profile.active,profile.updatedAt?'No accepted active membership is present in the observed records.':'Table history is still loading.')}{profile.pending.length>0&&<details><summary>Waiting on membership · {profile.pending.length}</summary>{tables(profile.pending,'')}</details>}{profile.hosted.length>0&&<details><summary>Tables I host · {profile.hosted.length}</summary>{tables(profile.hosted,'')}</details>}</section>
 <section className="profile-section"><h3><Trophy size={19}/> Accepted poem history</h3>{!profile.historyReady&&<p className="inline-info">Some submission history is still being reconciled. Verified credits already found count now; a + means at least this many. With no verified credits, the rank remains pending.</p>}{tables(profile.completed,profile.historyReady?'No accepted poem submissions are recorded for this DID yet.':'Verified completions will appear here.')}<p className="fine-print">One credit per accepted poem and room generation, for its verified contributors. Filling a table or finishing a draft earns no credit. Submission acceptance is separate from winning an award.</p></section>
 <section className="profile-section"><h3><Vote size={19}/> My ballot</h3>{profile.currentVote?<div className="current-ballot"><span>Latest accepted choice</span><strong>{profile.currentVote.entry}</strong><a href={roomLink(profile.currentVote.receipt!.room,profile.currentVote.receipt!.seq)} target="_blank" rel="noreferrer">Accepted ballot evidence<ArrowUpRight size={14}/></a></div>:<p className="profile-empty">{profile.person?.role==='writer'||profile.person?.role==='organizer'?`Your registered role is ${profile.person.role}. This role cannot vote.`:'No accepted ballot was found for this DID in the observed records.'}</p>}
 {profile.ballots.length>0&&<details><summary>Recent ballot history · {profile.ballots.length}</summary><ol className="profile-votes">{profile.ballots.map(b=><li key={`${b.request.room}:${b.request.seq}`}><strong>{b.entry}</strong><span>{b.status==='accepted'?(b.request.seq===profile.currentVote?.request.seq?'Latest accepted choice':'Earlier accepted choice'):b.status==='rejected'?'Rejected · did not replace your vote':'Waiting for referee'}</span><time>{new Date(b.at).toLocaleString('en-GB',{timeZone:'UTC',dateStyle:'medium',timeStyle:'short'})} UTC</time>{b.reason&&<p>{b.reason}</p>}<a href={roomLink((b.receipt??b.request).room,(b.receipt??b.request).seq)} target="_blank" rel="noreferrer">View signed record<ExternalLink size={13}/></a></li>)}</ol></details>}
 <p className="fine-print">A newer accepted ballot replaces the previous choice. Rejected attempts do not. Final eligibility and official results can still change which votes count.</p></section>
 </div></div><footer className="profile-footnote"><CheckCheck size={16}/><span>Sonnet 2 · public records observed through {profile.updatedAt?new Date(profile.updatedAt).toLocaleString('en-GB',{timeZone:'UTC',dateStyle:'medium',timeStyle:'short'})+' UTC':'the next index refresh'}. Retained history may be incomplete. {profile.warning}</span></footer></>}
 </section>;
}

function AchievementBadge({profile,verified,notify}:{profile:Profile;verified:boolean;notify:(text:string)=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),[file,setFile]=useState<File|null>(null),[error,setError]=useState('');
 const tier=profileTier(profile),n=profile.completed.length;
 const recordKey=JSON.stringify([profile.did,profile.person?.name,profile.person?.role,profile.person?.registration,profile.historyReady,n,profile.active.length,profile.updatedAt]);
 useEffect(()=>{let active=true;setFile(null);setError('');if(canvas.current)void renderProfileCard(canvas.current,profile).then(blob=>{if(active)setFile(new File([blob],`sonnet-tables-${profile.did.slice(-10)}-${tier}.png`,{type:'image/png'}));}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[recordKey]);
 const shareUrl=()=>`${location.origin}${location.pathname}#profile/${encodeURIComponent(profile.did)}`;
 const canShare=verified&&!!file;
 function download(){if(!file)return;const url=URL.createObjectURL(file);const link=document.createElement('a');link.href=url;link.download=file.name;link.click();setTimeout(()=>URL.revokeObjectURL(url),30000);notify('Badge image saved. Attach it to your X post.');}
 async function share(){if(!file)return;try{if(navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:'My Sonnet Tables badge',text:profileShareText(profile),url:shareUrl()});}else download();}catch(e){if((e as Error).name!=='AbortError'){download();}}}
 return <div className="badge-studio"><div className={`achievement-card tier-${tier}`} onPointerMove={e=>{if(e.pointerType!=='mouse'||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--tilt-x',`${(e.clientY-r.top-r.height/2)/r.height*-5}deg`);e.currentTarget.style.setProperty('--tilt-y',`${(e.clientX-r.left-r.width/2)/r.width*5}deg`);}} onPointerLeave={e=>{e.currentTarget.style.setProperty('--tilt-x','0deg');e.currentTarget.style.setProperty('--tilt-y','0deg');}}><canvas ref={canvas} width={1200} height={1600} role="img" aria-label={`${tier} robot achievement badge for ${profile.person?.name??shortDid(profile.did)}. ${n?(profile.historyReady?'':'At least ')+n+' accepted poem submissions':profile.historyReady?'No accepted poems observed':'History verification pending'}.`}/>{!file&&!error&&<span className="badge-rendering"><LoaderCircle className="spin" size={20}/>Preparing your badge</span>}</div>
 <div className="badge-caption"><span className={`badge-tier-name tier-${tier}`}>{tier==='unverified'?'History pending':`${tier[0].toUpperCase()+tier.slice(1)} edition`}</span><p>Bronze · 0 accepted poems<br/>Silver · 1 accepted poem<br/>Gold · 2 or more accepted poems</p></div>
 {error&&<p className="inline-warning">{error}</p>}
 <div className="badge-actions"><button className="button primary" disabled={!canShare} onClick={download}><Download size={17}/>Save badge PNG</button><button className="button" disabled={!canShare} onClick={()=>void share()}><Share2 size={17}/>Share image</button><a className={`button ${!canShare?'badge-disabled':''}`} aria-disabled={!canShare} tabIndex={canShare?0:-1} href={canShare?`https://x.com/intent/post?${new URLSearchParams({text:profileShareText(profile),url:shareUrl()})}`:undefined} target="_blank" rel="noreferrer"><ExternalLink size={17}/>Prepare X post</a><button className="text-button" onClick={async()=>{try{await navigator.clipboard.writeText(shareUrl());notify('Public profile link copied.');}catch{notify('Copy the profile address from your browser.');}}}><Copy size={15}/>Copy public profile link</button></div>
 <p className="fine-print">{!verified?'Verify your existing key to export your own badge. ':''}Save the image, then attach it in X. The post includes your public profile link. This is a shareable achievement image, not a minted token or an official award.</p>
 </div>;
}
