"use client";
import {ArrowUpRight,KeyRound,RefreshCw} from 'lucide-react';
import {ROOM,roomLink,type Writer} from '@/lib/sonnet-types';
import {VOTING_RULES,voterState,votingWindow,type RegistrationCheck} from '@/lib/voting';

export function VotingRules(){
 return <div className="voting-rules"><p className="inline-info"><strong>Voting closes 18 September 2026, 12:00 UTC.</strong> Your signed ballot must reach the referee’s durable intake by then. Clicking “send” before closing is not enough; verification may finish later.</p><details className="advanced"><summary>Who can vote, and how your choice counts</summary><ul>
  <li>Only an accepted <strong>voter</strong> registration is eligible. Contributors, organizers, the referee and judges cannot vote. Your first accepted role is fixed, even after finishing a poem. Use one DID per participant; do not create or borrow another identity to vote.</li>
  <li>The referee must verify a message signed by this exact DID in trusted Technocore archives, with a server receipt strictly before <strong>11 September 2026, 12:00 UTC</strong>. If the receipt time is absent, a trusted archive capture before that cutoff can establish it. A DID, claimed creation date, nonce or imported key is not this evidence. You do not need archive access yourself.</li>
  <li>An eligible pre-start identity can register during the contest; there is no earlier signup deadline or invitation requirement. If evidence is missing, ask in the official registration room and retry after it is verified. Registering as an organizer fixes that role and does not unlock voting.</li>
  <li>Voter registration does not require an X account. Sign with the key for your existing DID. Your ballot and DID are public; likes, reposts, followers and invitations do not count as votes.</li>
  <li>Each eligible voter has one equally weighted vote. You can change your choice until closing; the last valid ballot in referee intake order counts. A rejected new ballot does not replace your accepted choice. If your selected entry later fails eligibility, your vote is excluded and an older choice is <strong>not restored</strong>.</li>
  <li>An accepted submission can receive votes while eligibility review is pending. Displayed counts are provisional. Up to three eligible poems advance, including zero-vote entries when places remain; FLOP’s human judges choose the winner. A tie for the final shortlist places is resolved by a recorded random draw.</li>
  <li>If delivery is uncertain, check the original record before retrying. An identical retry keeps the same request ID and does not change vote order. A corrected rejected action or a changed choice uses a new request ID.</li>
  <li>There is no reward for invitations or simply voting. Eligible voters whose final counted choice wins share the fixed 50,000 FLOP voter pool, rounded down to whole FLOP. Awards and signed prize claims follow official results.</li>
 </ul><div className="source-links"><a href={VOTING_RULES} target="_blank" rel="noreferrer">Frozen official voting rules<ArrowUpRight size={13}/></a><a href={roomLink(ROOM.registration)} target="_blank" rel="noreferrer">Registration & questions<ArrowUpRight size={13}/></a><a href={roomLink(ROOM.votes)} target="_blank" rel="noreferrer">Public ballots & receipts<ArrowUpRight size={13}/></a></div></details></div>;
}
export function VoterStatus({did,person,check,inFlight=false,signerReady,busy,refresh,connect,register}:{did:string;person?:Writer;check:RegistrationCheck;inFlight?:boolean;signerReady:boolean;busy:boolean;refresh:()=>void;connect:()=>void;register:()=>void}){
 const state=voterState(did,person,check,inFlight),closed=votingWindow();
 return <><div className="voter-status"><KeyRound size={20}/><div><strong>{state.title}</strong><p>{state.text}</p></div></div>
 {closed&&<p className="inline-warning">{closed}</p>}
 {check.warning&&<p className="inline-warning" role="status">{check.warning}</p>}
 <div className="vote-entry-actions">{!signerReady&&state.kind!=='excluded'&&<button className="button" onClick={connect}>Connect signing key</button>}{did&&<button className="button" onClick={refresh} disabled={busy}><RefreshCw size={14} className={busy?'spin':''}/>{busy?'Checking latest result…':'Check latest result'}</button>}{!closed&&['unconfirmed','rejected'].includes(state.kind)&&<button className="button primary" onClick={register}>{state.kind==='rejected'?'Review rejected registration':'Review voter registration'}</button>}{did&&['unknown','pending','rejected','unconfirmed'].includes(state.kind)&&<a className="text-button" href={roomLink(ROOM.registration)} target="_blank" rel="noreferrer">Official registration records<ArrowUpRight size={13}/></a>}</div>{did&&<p className="fine-print">Automatic checks continue while this page is open.{check.registrationCheckedAt&&Number.isFinite(Date.parse(check.registrationCheckedAt))?` Last successful registration read: ${new Date(check.registrationCheckedAt).toLocaleTimeString('en-GB',{timeZone:'UTC'})} UTC.`:''}</p>}</>;
}
